#!/bin/bash
# Wed Jan 08 2020 14:16:24 GMT+1100 (Australian Eastern Daylight Time)

# Partition for the job:
#SBATCH --partition=gpgpu

# Multithreaded (SMP) job: must run on one node and the cloud partition
#SBATCH --nodes=4

# The name of the job:
#SBATCH --job-name="oct3"

# The project ID which this job should run under:
#SBATCH --account="punim0524"

# Maximum number of tasks/CPU cores used by the job:
#SBATCH --ntasks-per-node=4
#SBATCH --cpus-per-task=1

# Number of GPUs requested per node:
#SBATCH --gres=gpu:4

# The amount of memory in megabytes per process in the job:
#SBATCH --mem=10192

# Use this email address:
##SBATCH --mail-user=tonyzahtila@gmail.com

#SBATCH --output="case.out"

# The maximum running time of the job in days-hours:mins:sec
#SBATCH --time=0-12:0:00

# check that the script is launched with sbatch
if [ "x$SLURM_JOB_ID" == "x" ]; then
   echo "You need to submit your job to the queuing system with sbatch"
   exit 1
fi

# Run the job from the directory where it was launched (default)

source /usr/local/module/spartan_new.sh
module load gompic/2019b
module load cmake/3.18.4

#module load OpenMPI/3.1.0-intel-2017.u2-GCC-6.2.0-cuda9-tcp
#module load CMake/3.12.1-intel-2017.u2-GCC-6.2.0-CUDA9

export NEKRS_HOME=$HOME/.local/nekrs
PATH=${NEKRS_HOME}/bin:${PATH}
#source $HOME/.bash_profile

#export NEKRS_HYPRE_NUM_THREADS=1
#export OGS_MPI_SUPPORT=1
#bin=$NEKRS_HOME/bin/nekrs

#export USE_UCX=0
export UCX_MEM_MMAP_RELOC=n
export UCX_MEM_MALLOC_HOOKS=n
export UCX_MEM_MALLOC_RELOC=n
export UCX_MEM_EVENTS=n
export UCX_MEMTYPE_CACHE=n

backend=CUDA

#srun $NEKRS_HOME/bin/nekrs --setup turbPipe
env | grep 'UCX\|OMPI' | sort
nrsmpi turbPipe 16
